import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,Session} from '@supabase/supabase-js';
import {Activity,Shield,Search,LogOut,BarChart3,CloudRain,ChevronRight,Lock,RefreshCw} from 'lucide-react';
import {analyzeMatch} from './services/engine';
import './styles.css';

const url=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined;
const supabase=url&&key?createClient(url,key):null;

type Analysis={status:'approved'|'rejected';match:string;market:string;line:string;odd:number;probability:number;implied:number;edge:number;ev:number;confidence:number;robustness:string;risk:string;classification:string;reasons:string[];risks:string[]};

function Auth({onSession}:{onSession:(s:Session)=>void}){const [login,setLogin]=useState(true);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 if(!supabase)return <div className="center"><div className="card auth"><Lock/><h1>NewTips</h1><p>Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY para habilitar o acesso.</p></div></div>;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');const r=login?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setError(r.error.message);else if(r.data.session)onSession(r.data.session);setBusy(false)};
 return <div className="center"><div className="card auth"><div className="brand"><span className="logo">N</span><div><b>NEWTIPS</b><small>QUANTITATIVE INTELLIGENCE</small></div></div><h1>{login?'Entrar':'Criar conta'}</h1><p>Acesso seguro ao terminal de inteligência esportiva.</p><form onSubmit={submit}><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?'Autenticando…':login?'Entrar':'Cadastrar'} <ChevronRight size={17}/></button></form><button className="link" onClick={()=>setLogin(!login)}>{login?'Ainda não tenho conta':'Já tenho conta'}</button></div></div>}

function App(){const [session,setSession]=useState<Session|null>(null);const [home,setHome]=useState('dashboard');const [match,setMatch]=useState({home:'',away:'',date:'',competition:''});const [odd,setOdd]=useState('1.70');const [analysis,setAnalysis]=useState<Analysis|null>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 if(!session)return <Auth onSession={setSession}/>;
 const run=async()=>{if(!match.home||!match.away||!match.date)return;setLoading(true);setAnalysis(null);const result=await analyzeMatch(match,Number(odd));setAnalysis(result);setLoading(false)};
 return <div className="app"><aside><div className="brand"><span className="logo">N</span><div><b>NEWTIPS</b><small>QUANT INTELLIGENCE</small></div></div><nav><button className={home==='dashboard'?'active':''} onClick={()=>setHome('dashboard')}><Activity/>Terminal</button><button className={home==='history'?'active':''} onClick={()=>setHome('history')}><BarChart3/>Histórico</button><button className={home==='admin'?'active':''} onClick={()=>setHome('admin')}><Shield/>Administração</button></nav><button className="logout" onClick={()=>supabase?.auth.signOut()}><LogOut/>Sair</button></aside><main><header><div><span className="eyebrow">PRE-MATCH ANALYTICS / V3</span><h1>Terminal de análise</h1></div><div className="status"><i/> ENGINE ONLINE</div></header>{home==='dashboard'&&<><section className="hero"><div><h2>Descubra a assimetria.</h2><p>O motor coleta contexto, modela probabilidades, testa mercados e tenta destruir a própria tese antes de decidir.</p></div><div className="heroMetric"><span>MODELO</span><b>V3</b><small>RED TEAM ENABLED</small></div></section><section className="grid"><div className="card form"><div className="cardTitle"><span><Search/>Confronto</span><em>INPUT MÍNIMO</em></div><label>Competição<input value={match.competition} onChange={e=>setMatch({...match,competition:e.target.value})} placeholder="Ex.: Brasileirão Série A"/></label><div className="cols"><label>Mandante<input value={match.home} onChange={e=>setMatch({...match,home:e.target.value})} placeholder="Time mandante"/></label><label>Visitante<input value={match.away} onChange={e=>setMatch({...match,away:e.target.value})} placeholder="Time visitante"/></label></div><div className="cols"><label>Data<input type="date" value={match.date} onChange={e=>setMatch({...match,date:e.target.value})}/></label><label>Odd de referência<input type="number" min="1.01" step="0.01" value={odd} onChange={e=>setOdd(e.target.value)}/></label></div><button className="primary" onClick={run} disabled={loading}>{loading?<><RefreshCw className="spin"/>Processando motor…</>:<>Executar análise <ChevronRight/></>}</button></div><div className="card telemetry"><div className="cardTitle"><span><CloudRain/>Telemetria</span><em>OPEN-METEO</em></div><div className="telemetryBox"><b>Condições externas</b><span>Consultadas durante a análise</span><small>Temperatura · vento · precipitação</small></div><div className="telemetryBox"><b>Dados críticos</b><span>Validação multi-fonte</span><small>Escalação · árbitro · calendário · forma</small></div></div></section>{analysis&&<AnalysisView data={analysis}/>}</>}{home!=='dashboard'&&<div className="card empty"><Shield/><h2>{home==='admin'?'Painel administrativo':'Histórico de análises'}</h2><p>O módulo está protegido e será conectado ao Supabase quando o backend for provisionado.</p></div>}</main></div>}
function AnalysisView({data}:{data:Analysis}){return <section className="card result"><div className="resultHead"><div><span className="eyebrow">DECISÃO NEWTIPS</span><h2>{data.status==='approved'?'🎯 ENTRADA NEWTIPS':'❌ SEM ENTRADA'}</h2></div><div className="badge">{data.classification}</div></div><div className="stats"><Metric k="Mercado" v={data.market}/><Metric k="Odd" v={data.odd.toFixed(2)}/><Metric k="Probabilidade" v={`${data.probability.toFixed(1)}%`}/><Metric k="Edge" v={`${data.edge>=0?'+':''}${data.edge.toFixed(1)} p.p.`}/><Metric k="EV" v={`${data.ev>=0?'+':''}${data.ev.toFixed(1)}%`}/><Metric k="Confiança" v={`${data.confidence}/100`}/></div><div className="cols resultCols"><div><h3>Por que essa decisão?</h3>{data.reasons.map(x=><p className="bullet" key={x}>{x}</p>)}</div><div><h3>Red Team — riscos</h3>{data.risks.map(x=><p className="bullet danger" key={x}>{x}</p>)}</div></div></section>}
function Metric({k,v}:{k:string,v:string}){return <div className="metric"><span>{k}</span><b>{v}</b></div>}
createRoot(document.getElementById('root')!).render(<App/>);